# Academic Database - SQLite Docker Compose
# This is the simple deployment option using SQLite
# for quick setup and development use.

version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=academicdb_web.settings.docker
      - USE_POSTGRES=false
      - DEBUG=false
      - SECRET_KEY=your-secret-key-here-change-in-production
      - SQLITE_PATH=/app/data/db.sqlite3
      # Optional: Create superuser on startup
      # - DJANGO_SUPERUSER_USERNAME=admin
      # - DJANGO_SUPERUSER_EMAIL=admin@example.com
      # - DJANGO_SUPERUSER_PASSWORD=admin_password
    volumes:
      - sqlite_data:/app/data
      - media_files:/app/media
      - static_files:/app/staticfiles
      - app_logs:/app/logs
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local
  media_files:
    driver: local
  static_files:
    driver: local
  app_logs:
    driver: local