# Generated by Django 4.2.24 on 2025-09-12 18:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Digital Object Identifier (DOI)",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Publication title (minimum 10 characters)",
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        db_index=True,
                        help_text="Publication year",
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True,
                        help_text="Specific publication date if known",
                        null=True,
                    ),
                ),
                (
                    "publication_name",
                    models.CharField(
                        blank=True,
                        help_text="Journal, conference, or publisher name",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("journal-article", "Journal Article"),
                            ("conference-paper", "Conference Paper"),
                            ("book", "Book"),
                            ("book-chapter", "Book Chapter"),
                            ("preprint", "Preprint"),
                            ("thesis", "Thesis/Dissertation"),
                            ("patent", "Patent"),
                            ("report", "Report"),
                            ("dataset", "Dataset"),
                            ("software", "Software"),
                            ("other", "Other"),
                        ],
                        default="journal-article",
                        help_text="Type of publication",
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="API-specific metadata (Scopus, PubMed, etc.)",
                    ),
                ),
                (
                    "authors",
                    models.JSONField(
                        default=list, help_text="List of authors with affiliations"
                    ),
                ),
                (
                    "identifiers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="External identifiers (PMID, PMCID, Scopus ID, etc.)",
                    ),
                ),
                (
                    "links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="URLs to PDF, dataset, code repository, etc.",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("scopus", "Scopus"),
                            ("pubmed", "PubMed"),
                            ("crossref", "CrossRef"),
                            ("orcid", "ORCID"),
                            ("manual", "Manual Entry"),
                        ],
                        default="manual",
                        help_text="Original data source",
                        max_length=50,
                    ),
                ),
                (
                    "manual_edits",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tracks which fields have been manually edited",
                    ),
                ),
                (
                    "edit_history",
                    models.JSONField(
                        blank=True, default=list, help_text="Audit trail of all edits"
                    ),
                ),
                (
                    "manually_edited_at",
                    models.DateTimeField(
                        blank=True, help_text="Last manual edit timestamp", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_api_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last synchronization with external API",
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "ordering": ["-year", "-publication_date", "title"],
                "indexes": [
                    models.Index(
                        fields=["owner", "year"], name="academic_pu_owner_i_830639_idx"
                    ),
                    models.Index(fields=["doi"], name="academic_pu_doi_cbe44c_idx"),
                    models.Index(
                        fields=["source", "updated_at"],
                        name="academic_pu_source_d5abc0_idx",
                    ),
                ],
                "unique_together": {("owner", "doi")},
            },
        ),
    ]
