# Generated by Django 4.2.24 on 2025-09-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="doi",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Digital Object Identifier (DOI)",
                max_length=255,
                null=True,
            ),
        ),
    ]
