# Generated by Django 4.2.24 on 2025-09-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_alter_publication_doi"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicuser",
            name="scopus_id",
            field=models.CharField(
                blank=True, help_text="Scopus Author ID", max_length=20, null=True
            ),
        ),
    ]
