# Generated by Django 4.2.24 on 2025-09-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_academicuser_scopus_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicuser",
            name="pubmed_query",
            field=models.TextField(
                blank=True,
                help_text="PubMed search query to find your publications (e.g., 'Smith J[Author] AND Stanford[Affiliation]')",
                null=True,
            ),
        ),
    ]
