# Generated by Django 4.2.24 on 2025-09-13 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0006_authorcache"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("agency", models.CharField(max_length=200)),
                ("grant_number", models.CharField(blank=True, max_length=100)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Funding amount in the specified currency",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Project start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Project end date", null=True
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("pi", "Principal Investigator"),
                            ("co_pi", "Co-Principal Investigator"),
                            ("co_i", "Co-Investigator"),
                            ("consultant", "Consultant"),
                            ("other", "Other"),
                        ],
                        default="pi",
                        help_text="Your role in this funding",
                        max_length=50,
                    ),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (ORCID-specific fields, etc.)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                            ("declined", "Declined"),
                        ],
                        default="active",
                        help_text="Current status of the funding",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("orcid", "ORCID"),
                            ("manual", "Manual Entry"),
                            ("institutional", "Institutional System"),
                        ],
                        default="manual",
                        help_text="Original data source",
                        max_length=50,
                    ),
                ),
                (
                    "manual_edits",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tracks which fields have been manually edited",
                    ),
                ),
                (
                    "edit_history",
                    models.JSONField(
                        blank=True, default=list, help_text="Audit trail of all edits"
                    ),
                ),
                (
                    "manually_edited_at",
                    models.DateTimeField(
                        blank=True, help_text="Last manual edit timestamp", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_api_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last synchronization with external API",
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Funding",
                "verbose_name_plural": "Funding",
                "ordering": ["-start_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "start_date"],
                        name="academic_fu_owner_i_0f0067_idx",
                    ),
                    models.Index(
                        fields=["agency", "status"],
                        name="academic_fu_agency_2ad19a_idx",
                    ),
                    models.Index(
                        fields=["source", "updated_at"],
                        name="academic_fu_source_6de75d_idx",
                    ),
                ],
            },
        ),
    ]
