# Generated by Django 4.2.24 on 2025-09-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0008_teaching_talk_conference"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="is_preprint",
            field=models.BooleanField(
                default=False,
                help_text="True if this publication is a preprint (detected from DOI or manually set)",
            ),
        ),
    ]
