# Generated by Django 4.2.24 on 2025-09-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0009_add_preprint_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="ignore_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason for ignoring this publication (optional)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="is_ignored",
            field=models.BooleanField(
                default=False,
                help_text="True if this publication should be ignored (e.g., corrigendum, misattributed)",
            ),
        ),
    ]
