# Generated by Django 4.2.24 on 2025-09-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0010_add_publication_ignore_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funding",
            name="role",
            field=models.CharField(
                choices=[
                    ("pi", "Principal Investigator"),
                    ("pi_subcontract", "PI (Subcontract)"),
                    ("co_pi", "Co-Principal Investigator"),
                    ("co_i", "Co-Investigator"),
                    ("consultant", "Consultant"),
                    ("other", "Other"),
                ],
                default="pi",
                help_text="Your role in this funding",
                max_length=50,
            ),
        ),
    ]
