# Generated by Django 4.2.24 on 2025-09-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0011_add_pi_subcontract_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicuser",
            name="skip_dois",
            field=models.TextField(
                blank=True,
                help_text="List of DOIs to skip during publication ingestion (one per line)",
                null=True,
            ),
        ),
    ]
