# Generated by Django 4.2.24 on 2025-09-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic",
            "0015_professionalactivity_remove_funding_funding_info_gin_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="academicuser",
            name="address1",
            field=models.CharField(
                blank=True, help_text="Street address line 1", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="academicuser",
            name="address2",
            field=models.CharField(
                blank=True,
                help_text="Street address line 2 (apartment, suite, etc.)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="academicuser",
            name="city",
            field=models.CharField(blank=True, help_text="City", max_length=100),
        ),
        migrations.AddField(
            model_name="academicuser",
            name="country",
            field=models.CharField(blank=True, help_text="Country", max_length=100),
        ),
        migrations.AddField(
            model_name="academicuser",
            name="middle_name",
            field=models.CharField(
                blank=True,
                help_text="Middle name or initial for CV formatting",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="academicuser",
            name="phone",
            field=models.CharField(blank=True, help_text="Phone number", max_length=20),
        ),
        migrations.AddField(
            model_name="academicuser",
            name="state",
            field=models.CharField(
                blank=True, help_text="State or province", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="academicuser",
            name="websites",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of websites/URLs with labels (e.g., [{'label': 'Personal Website', 'url': 'https://...'}])",
            ),
        ),
        migrations.AddField(
            model_name="academicuser",
            name="zip_code",
            field=models.CharField(
                blank=True, help_text="ZIP or postal code", max_length=20
            ),
        ),
    ]
