# Generated by Django 4.2.24 on 2025-09-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0016_add_address_contact_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="page_range",
            field=models.CharField(
                blank=True,
                help_text="Page range (e.g., '123-135', '1-15', 'e12345')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="volume",
            field=models.CharField(
                blank=True, help_text="Journal volume number", max_length=50, null=True
            ),
        ),
    ]
