# Generated by Django 4.2.24 on 2025-09-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0018_populate_volume_page_range"),
    ]

    operations = [
        migrations.CreateModel(
            name="PMCCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pmid",
                    models.CharField(
                        db_index=True, help_text="PubMed ID", max_length=20, unique=True
                    ),
                ),
                (
                    "pmcid",
                    models.CharField(
                        help_text="PubMed Central ID (with PMC prefix)", max_length=20
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="DOI associated with this publication",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "lookup_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of times this mapping has been used",
                    ),
                ),
                (
                    "last_verified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this mapping was verified/updated",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pubmed_api", "PubMed API"),
                            ("manual", "Manual Entry"),
                        ],
                        default="pubmed_api",
                        help_text="Source of the mapping",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "PMC Cache Entry",
                "verbose_name_plural": "PMC Cache Entries",
                "ordering": ["-lookup_count", "-last_verified"],
                "indexes": [
                    models.Index(fields=["pmid"], name="academic_pm_pmid_ab4b51_idx"),
                    models.Index(fields=["pmcid"], name="academic_pm_pmcid_58240f_idx"),
                    models.Index(fields=["doi"], name="academic_pm_doi_b54769_idx"),
                    models.Index(
                        fields=["lookup_count", "-last_verified"],
                        name="academic_pm_lookup__92d30f_idx",
                    ),
                ],
            },
        ),
    ]
