# Generated by Django 4.2.24 on 2025-09-16 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0021_update_search_vector_include_authors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Code", "Code"),
                            ("Data", "Data"),
                            ("OSF", "OSF"),
                            ("Other", "Other"),
                        ],
                        help_text="Type of link (Code, Data, OSF, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        db_index=True,
                        help_text="DOI of the publication this link belongs to",
                        max_length=255,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL of the linked resource", max_length=1000
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title/description for the link",
                        max_length=500,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("csv_import", "CSV Import"),
                            ("manual", "Manual Entry"),
                        ],
                        default="csv_import",
                        help_text="How this link was added",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Link",
                "verbose_name_plural": "Links",
                "ordering": ["type", "doi"],
                "indexes": [
                    models.Index(
                        fields=["owner", "doi"], name="academic_li_owner_i_e0c89f_idx"
                    ),
                    models.Index(
                        fields=["type", "doi"], name="academic_li_type_be5a53_idx"
                    ),
                ],
                "unique_together": {("owner", "doi", "type", "url")},
            },
        ),
    ]
