# Generated by Django 4.2.24 on 2025-09-17 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0022_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Editorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Editorial role (e.g., Senior Editor, Editorial board, Handling Editor)",
                        max_length=200,
                    ),
                ),
                (
                    "journal",
                    models.CharField(
                        help_text="Journal or publication name", max_length=300
                    ),
                ),
                (
                    "dates",
                    models.CharField(
                        blank=True,
                        help_text="Date range for the editorial role (e.g., '2020-2024', '2024-')",
                        max_length=100,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("csv_import", "CSV Import"),
                            ("manual", "Manual Entry"),
                        ],
                        default="csv_import",
                        help_text="How this editorial activity was added",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editorial_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Editorial Activity",
                "verbose_name_plural": "Editorial Activities",
                "ordering": ["role", "journal"],
                "indexes": [
                    models.Index(
                        fields=["owner", "role"], name="academic_ed_owner_i_79ee6d_idx"
                    ),
                    models.Index(
                        fields=["journal", "role"],
                        name="academic_ed_journal_5c6ad0_idx",
                    ),
                ],
            },
        ),
    ]
