# Generated by Django 4.2.24 on 2025-09-17 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0023_add_editorial_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scopus_id",
                    models.CharField(help_text="Scopus Author ID", max_length=20),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the collaborator", max_length=300
                    ),
                ),
                (
                    "affiliation",
                    models.CharField(
                        blank=True,
                        help_text="Current institutional affiliation",
                        max_length=500,
                    ),
                ),
                (
                    "affiliation_id",
                    models.CharField(
                        blank=True, help_text="Scopus Affiliation ID", max_length=20
                    ),
                ),
                (
                    "last_publication_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of most recent collaboration",
                        null=True,
                    ),
                ),
                (
                    "publication_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of shared publications"
                    ),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional collaborator details from Scopus API",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("scopus_api", "Scopus API"),
                            ("manual", "Manual Entry"),
                        ],
                        default="scopus_api",
                        help_text="How this collaborator was added",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collaborator",
                "verbose_name_plural": "Collaborators",
                "ordering": ["-last_publication_date", "name"],
                "indexes": [
                    models.Index(
                        fields=["owner", "scopus_id"],
                        name="academic_co_owner_i_c35de1_idx",
                    ),
                    models.Index(
                        fields=["owner", "last_publication_date"],
                        name="academic_co_owner_i_f3fd2a_idx",
                    ),
                ],
            },
        ),
    ]
