# Generated by Django 4.2.24 on 2025-09-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0024_collaborator"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conference",
            name="academic_co_year_a5cd11_idx",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="abstract",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="additional_info",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="conference_name",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="manual_edits",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="parsed_authors",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="presentation_type",
        ),
        migrations.AlterField(
            model_name="conference",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual Entry"), ("csv_import", "CSV Import")],
                default="manual",
                help_text="Original data source",
                max_length=50,
            ),
        ),
    ]
