# Generated by Django 4.2.24 on 2025-09-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0025_simplify_conference_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="talk",
            options={
                "ordering": ["-year", "place"],
                "verbose_name": "Talk",
                "verbose_name_plural": "Talks",
            },
        ),
        migrations.RemoveIndex(
            model_name="talk",
            name="academic_ta_year_907133_idx",
        ),
        migrations.RemoveField(
            model_name="talk",
            name="additional_info",
        ),
        migrations.RemoveField(
            model_name="talk",
            name="date",
        ),
        migrations.RemoveField(
            model_name="talk",
            name="manual_edits",
        ),
        migrations.RemoveField(
            model_name="talk",
            name="title",
        ),
        migrations.RemoveField(
            model_name="talk",
            name="virtual",
        ),
        migrations.AlterField(
            model_name="talk",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual Entry"), ("csv_import", "CSV Import")],
                default="manual",
                help_text="Original data source",
                max_length=50,
            ),
        ),
    ]
